# .github/workflows/main.yml

name: Deploy Cloud Function

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          # Replace with your Workload Identity Provider Location
          workload_identity_provider: "projects/967529915926/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          # Replace with your GitHub Service Account
          service_account: "policy-tag-governance@astra-digital-governance.iam.gserviceaccount.com"

      - id: "setup-python"
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - id: "requirements"
        name: Install dependencies
        run: pip install -r requirements.txt

      - id: "deploy"
        name: Deploy Cloud Function
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: dataplex_pubsub
          runtime: python37
          entry_point: dataplex_pubsub
          region: asia-southeast2
          service_account_email: policy-tag-governance@astra-digital-governance.iam.gserviceaccount.com
          ingress_settings: ALLOW_ALL
          memory_mb: "4096MB"
          timeout: 540
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/astra-digital-governance/topics/dataplex_trigger_pubsub